#!/usr/bin/env bash

# $1 secret/foo/

delete_path()
{
    IFS=$'\n' values=($(vault kv list -format=json "$1" | jq -r '.[]'))

    if [ -z $values ]; then
        echo "delete $1"
        versions=$(vault kv metadata get -format=json $1 |jq '.data.versions | keys_unsorted[] | tonumber' | tr '\n' ',')
        vault kv destroy --versions=$versions $1
        vault kv metadata delete $1
    else
        for key in ${values[@]} ; do
            echo enter: "$1$key"
            delete_path "$1$key"
        done
        
        echo "delete $1";    
    fi
}

delete_path "$1"
