#!/usr/bin/env bash

CRT_FILE=${1:-/etc/vault-machine-*.soeren.cloud.krt}
KEY_FILE=${2:-/etc/vault-machine-*.soeren.cloud.key}

openssl pkcs12 -export -inkey "${KEY_FILE}" -in "${CRT_FILE}" -out ~/shred.p12
chown $(whoami)  ~/shred.p12
pk12util -d ~/.mozilla/firefox/*.default-release -i ~/shred.p12
shred -u ~/shred.p12

