#!/bin/sh

sudo openssl pkcs12 -export -inkey /etc/vault-machine-*.soeren.cloud.key -in /etc/vault-machine-*.soeren.cloud.crt -out ~/shred.p12
sudo chown soeren:soeren ~/shred.p12
pk12util -d ~/.mozilla/firefox/*.default-release -i ~/shred.p12
shred -u ~/shred.p12

