---
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        name: release
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: ${{ github.repository }}

  build-container:
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.release_created}}
    needs:
      - release-please
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Log in to the container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

      - name: Build and push container image
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-restic-container:
    runs-on: ubuntu-latest
    if: ${{needs.release-please.outputs.release_created}}
    needs:
      - release-please
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg_version: "17"
            image: ghcr.io/soerenschneider/restic
          - pg_version: "16"
            image: ghcr.io/soerenschneider/restic-pg16
          - pg_version: "15"
            image: ghcr.io/soerenschneider/restic-pg15
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v6.14.0
        with:
          context: restic
          build-args: |
            POSTGRES_MAJOR=${{ matrix.pg_version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
