---
name: Build & publish restic container images
on:
  push:
    paths:
      - 'restic/restic**'
      - 'restic/Dockerfile**'
    branches:
      - main
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg_version: "17"
            image: ghcr.io/soerenschneider/restic
          - pg_version: "16"
            image: ghcr.io/soerenschneider/restic-pg16
          - pg_version: "15"
            image: ghcr.io/soerenschneider/restic-pg15
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value={{ branch}}-{{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and publish Docker image
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          build-args:
            - POSTGRES_MAJOR=${{ matrix.pg_version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
